function finishArcadeGame(){
 const a=finalBowlingScore(arcade.gA),b=finalBowlingScore(arcade.gB);recordArcadeGameScore(arcade.pA,a);recordArcadeGameScore(arcade.pB,b);arcade.gamesA.push(a);arcade.gamesB.push(b);arcade.commentary.push(`📺 Game ${arcade.gameIndex+1} final: ${arcade.pA.name} ${a}, ${arcade.pB.name} ${b}.`);arcade.gameIndex++;
 if(arcade.gameIndex<3){document.getElementById('arcadeStage').innerHTML=`<div class="game-intermission"><div class="broadcast-kicker">${playoffs.M[arcade.key].roundLabel}</div><h3>Game ${arcade.gameIndex} Complete</h3><div class="game-score">${arcade.pA.emoji} ${arcade.pA.name} ${a} · ${b} ${arcade.pB.name} ${arcade.pB.emoji}</div><p>Match aggregate: ${arcade.gamesA.reduce((x,y)=>x+y,0)}–${arcade.gamesB.reduce((x,y)=>x+y,0)}</p><div class="arcade-choice"><button class="primary" id="btnNextArcadeGame">Bowl Game ${arcade.gameIndex+1}</button><button class="ghost" onclick="window.__arcadeSimMatch()">Sim Rest of Match</button></div></div>`;document.getElementById('btnNextArcadeGame').addEventListener('click',startArcadeGame);}else finishArcadeMatch();
}
function recordArcadeGameScore(pl,score){pl.seasonGames.push(score);if(score>pl.allTimeHigh){const prev=pl.allTimeHigh;pl.allTimeHigh=score;logMilestone(`🎳 NEW CAREER HIGH — ${pl.emoji} ${pl.name} rolls ${score}, breaking the previous record of ${prev}!`);}}
function makeMatchResultFromArcade(){
 const totalA=arcade.gamesA.reduce((a,b)=>a+b,0),totalB=arcade.gamesB.reduce((a,b)=>a+b,0);let winner,loser,tiebreak=false;if(totalA===totalB){tiebreak=true;const pa=calcBlendedAvg(arcade.pA),pb=calcBlendedAvg(arcade.pB),prob=softmaxProb(pa,pb);winner=Math.random()<prob?arcade.pA:arcade.pB;loser=winner.id===arcade.pA.id?arcade.pB:arcade.pA;}else{winner=totalA>totalB?arcade.pA:arcade.pB;loser=winner.id===arcade.pA.id?arcade.pB:arcade.pA;}return {pA:arcade.pA,pB:arcade.pB,gamesA:arcade.gamesA.slice(),gamesB:arcade.gamesB.slice(),totalA,totalB,winner,loser,winScore:winner.id===arcade.pA.id?totalA:totalB,loseScore:winner.id===arcade.pA.id?totalB:totalA,tiebreak};
}
function finishArcadeMatch(){
 const res=makeMatchResultFromArcade();playoffs.recordsWL[res.winner.id]=(playoffs.recordsWL[res.winner.id]||0)+1;playoffs.recordsWL[res.loser.id]=(playoffs.recordsWL[res.loser.id]||0);commitMatch(arcade.key,res);renderBracket();const tie=res.tiebreak?'<p class="hint">Aggregate tie was decided by a skill-weighted one-ball roll-off.</p>':'';
 document.getElementById('arcadeStage').innerHTML=`<div class="game-intermission"><div class="broadcast-kicker">Match Final</div><h3>${res.winner.emoji} ${res.winner.name} wins ${playoffs.M[arcade.key].roundLabel}</h3><div class="game-score">${res.gamesA.join(' · ')} (${res.totalA}) &nbsp; vs &nbsp; ${res.gamesB.join(' · ')} (${res.totalB})</div>${tie}<p>Championship series: ${arcadeSeriesLabel()}</p><div class="arcade-choice">${playoffs.champion?'<button class="primary" id="btnShowTrophy">Trophy Ceremony</button>':'<button class="primary" id="btnNextFinalMatch">Continue Championship</button>'}<button class="ghost" onclick="window.__arcadeQuickSim()">Sim Rest</button></div></div>`;
 const trophy=document.getElementById('btnShowTrophy');if(trophy)trophy.addEventListener('click',renderTrophyCeremony);const next=document.getElementById('btnNextFinalMatch');if(next)next.addEventListener('click',startArcadeNextMatch);
}
function simRestOfArcadeGame(){
 arcadeClearTimers();const gsA=arcade.gA,gsB=arcade.gB;if(!gsA.complete){const score=simulateArcadeGameInstant(arcade.pA);gsA.frames=score.frames;gsA.complete=true;}if(!gsB.complete){const score=simulateArcadeGameInstant(arcade.pB);gsB.frames=score.frames;gsB.complete=true;}finishArcadeGame();
}
function simulateArcadeGameInstant(pl){const gs=newBowlingGame(pl);while(!gs.complete){const pins=chooseRollPins(pl,gs.pinsStanding,null);applyBowlingRoll(gs,pins);}return gs;}
function simArcadeMatch(){
 arcadeClearTimers();while(arcade.gamesA.length<3){const a=simulateArcadeGameInstant(arcade.pA),b=simulateArcadeGameInstant(arcade.pB),sa=finalBowlingScore(a),sb=finalBowlingScore(b);recordArcadeGameScore(arcade.pA,sa);recordArcadeGameScore(arcade.pB,sb);arcade.gamesA.push(sa);arcade.gamesB.push(sb);}finishArcadeMatch();
}
function quickSimArcadeFinals(){
 arcadeClearTimers();if(!arcade.active){arcade.active=true;const f=finalCompetitors();arcade.pA=f.A;arcade.pB=f.B;}
 if(arcade.key&&arcade.gamesA.length<3)simArcadeMatch();
 let guard=0;while(playoffs&&!playoffs.champion&&guard<6){const key=getNextPlayableMatchKey();if(!key)break;if(['GF1','GF2','GF3'].includes(key)){const res=resolveMatch(key);commitMatch(key,res);}else playNextMatch();guard++;}renderBracket();if(playoffs.champion)renderTrophyCeremony();
}
function renderTrophyCeremony(){
 if(!playoffs.champion)return;arcade.active=false;arcadeClearTimers();const c=playoffs.champion;const gf=['GF1','GF2','GF3'].map(k=>playoffs.M[k]).filter(m=>m&&m.result);const games=[];gf.forEach(m=>{const r=m.result;const arr=r.pA.id===c.id?r.gamesA:r.gamesB;games.push(...arr);});const best=games.length?Math.max(...games):'—';const avg=games.length?(games.reduce((a,b)=>a+b,0)/games.length).toFixed(1):'—';const conf=Array.from({length:55},(_,i)=>`<span class="confetti" style="left:${Math.random()*100}%;animation-duration:${2.7+Math.random()*3}s;animation-delay:${Math.random()*1.4}s;transform:rotate(${Math.random()*180}deg)"></span>`).join('');
 document.getElementById('arcadeTopTitle').textContent='Champion Crowned';document.getElementById('arcadeStage').innerHTML=`<div class="trophy-stage">${conf}<div class="champ-sub">BCM Bowling League Champion</div><div class="trophy-icon">🏆</div><div class="finalist-preview-wrap" style="margin:0 auto 8px;">${bowlerPreviewHtml(c,'mini preview','ready')}</div><h2>${c.emoji} ${c.name}</h2><div class="champ-sub">Seed #${c.seed} · Career Ring #${c.championships||1}</div><div class="trophy-stats"><div class="trophy-stat"><b>${playoffs.gfWins[c.id]||2}</b><span>Finals Match Wins</span></div><div class="trophy-stat"><b>${avg}</b><span>Finals Game Avg</span></div><div class="trophy-stat"><b>${best}</b><span>Best Finals Game</span></div></div><div class="arcade-choice"><button class="primary" id="btnCloseTrophy">Return to League</button><button class="ghost" onclick="window.__openSeasonArchive(${careerModeOn?careerYear:seasonNumber})">Open Season Archive</button></div></div>`;playArcadeSound('cheer');document.getElementById('btnCloseTrophy').addEventListener('click',closeArcadeModal);
}
function closeArcadeModal(){
 if(arcade.active&&!playoffs.champion){if(!confirm('Exit the championship broadcast? The remaining finals will be simulated so the season stays valid.'))return;quickSimArcadeFinals();if(!playoffs.champion)return;}
 arcade.active=false;arcadeClearTimers();document.getElementById('arcadeModal').classList.add('hidden');document.body.style.overflow='';renderBracket();if(playoffs.champion)showChampion();
}
function playArcadeSound(type){
 if(!arcade.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;window.__bcmAudio=window.__bcmAudio||new AC();const ctx=window.__bcmAudio;if(ctx.state==='suspended')ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);const now=ctx.currentTime;if(type==='roll'){o.type='sine';o.frequency.setValueAtTime(130,now);o.frequency.exponentialRampToValueAtTime(65,now+.25);g.gain.setValueAtTime(.045,now);g.gain.exponentialRampToValueAtTime(.001,now+.28);o.start(now);o.stop(now+.3);}else if(type==='cheer'){o.type='triangle';o.frequency.setValueAtTime(260,now);o.frequency.exponentialRampToValueAtTime(520,now+.45);g.gain.setValueAtTime(.055,now);g.gain.exponentialRampToValueAtTime(.001,now+.8);o.start(now);o.stop(now+.82);}else{o.type='square';o.frequency.setValueAtTime(type==='strike'?95:120,now);g.gain.setValueAtTime(.025,now);g.gain.exponentialRampToValueAtTime(.001,now+.18);o.start(now);o.stop(now+.2);}}catch(e){}
}
