/* BCM Bowling League v0.3.1d — A4 crowd, speed and bowling-physics patch */
(function(){
  const badge=document.querySelector('.build-badge');
  if(badge) badge.textContent='Beta v0.3.1d · A4 Frame 10 Fix';
  if(arcade.speed===undefined) arcade.speed=1;
  if(arcade.crowdSeed===undefined) arcade.crowdSeed=Math.floor(Math.random()*999999);

  function arcadeMs(ms){ return Math.max(35, Math.round(ms/Math.max(1,arcade.speed||1))); }
  function setArcadeSpeed(v){ arcade.speed=v; const b1=document.getElementById('btnSpeed1'), b2=document.getElementById('btnSpeed2'); if(b1) b1.classList.toggle('active',v===1); if(b2) b2.classList.toggle('active',v===2); }
  function crowdPalette(i){ const shirts=['#6f1f32','#2f6fda','#de7f25','#2d8b74','#b43333','#27446d','#c22d35','#f5f5f5']; const hairs=['#2b1d13','#4d3427','#814e2b','#1a1a1a','#8a6a46']; const skins=['#f0c7a3','#e0b18a','#c98b61','#f3d1b3']; return {shirt:shirts[i%shirts.length],hair:hairs[i%hairs.length],skin:skins[i%skins.length]}; }
  function renderChampionshipCrowd(){ const wrap=document.getElementById('arcadeCrowd'); if(!wrap) return; let html=''; const count=14; for(let i=0;i<count;i++){ const p=crowdPalette((arcade.crowdSeed+i)%23); const left=3+i*6.8+(i%2?1.4:-.8); const scale=0.8+((i%5)*0.05); const delay=(i%7)*.16; html += `<div class="crowd-character" style="left:${left}%;--shirt:${p.shirt};--hair:${p.hair};--skin:${p.skin};transform:scale(${scale});animation-delay:${delay}s;"><div class="spec-head"></div><div class="spec-hair"></div><div class="spec-body"></div><div class="spec-arm left"></div><div class="spec-arm right"></div></div>`; } html += `<div class="crowd-sign" style="left:50%;bottom:13px;transform:translateX(-50%);animation-delay:.3s;">BCM</div><div class="crowd-sign" style="left:78%;bottom:13px;animation-delay:.6s;">BENNY</div>`; wrap.innerHTML=html; }
  function setCrowdMood(mood='normal'){ const scene=document.querySelector('.lane-scene'); if(scene) scene.setAttribute('data-crowd', mood); }
  function pinIndexPool(){ return [0,1,2,3,4,5,6,7,8,9]; }
  function chooseFullRackLeave(count, meta={}){
    const line=meta.line||0, lefty=meta.lefty||false, heavyLeft=line<-18, pocketLeft=line<-2&&line>-18;
    const patterns={1:[[9],[6],[4]],2:[[5,9],[3,6],[4,7]],3:[[3,6,9],[5,8,9],[6,7,8]],4:[[4,5,8,9],[3,4,6,7],[1,3,6,9]],5:[[1,4,5,8,9],[1,3,4,6,7],[2,4,5,7,9]],6:[[1,2,4,5,7,9],[1,2,3,5,6,8],[2,3,4,6,7,9]],7:[[1,2,3,4,5,7,9],[0,2,3,4,5,6,8],[0,1,3,4,5,6,9]],8:[[0,1,2,3,4,5,7,9],[0,1,2,4,5,6,8,9]],9:[[0,1,2,3,4,5,6,7,9],[0,1,2,3,4,5,6,8,9]]};
    if(count<=0) return []; if(count>=10) return pinIndexPool();
    if(count in patterns){ let opts=patterns[count].map(a=>a.slice()); if(lefty||heavyLeft||pocketLeft) opts=opts.map(arr=>arr.map(i=>({0:0,1:2,2:1,3:5,4:4,5:3,6:9,7:8,8:7,9:6}[i]))); const pick=opts[(Math.abs(Math.round(line))+count)%opts.length]; return pick.slice(0,count).sort((a,b)=>a-b); }
    const full=pinIndexPool(); full.sort((a,b)=>Math.abs(a-4.5)-Math.abs(b-4.5)); return full.slice(-count).sort((a,b)=>a-b);
  }
  function reduceExistingLeave(cur,count,meta={}){ if(count<=0) return []; if(!cur||!cur.length) return []; if(count>=cur.length) return cur.slice(); const pos=pinPositions(); const targetX=50+(meta.line||0)*.28; return cur.slice().sort((a,b)=>Math.abs(pos[b][0]-targetX)-Math.abs(pos[a][0]-targetX)).slice(0,count).sort((a,b)=>a-b); }
  function makeVisualRollMeta(pl,before,pins,input,line){ const lefty=playerVisual(pl).handed==='left'; let type='fill'; if(before===10&&pins===10) type=Math.abs(line)>20?'brooklyn':'strike'; else if(before===10&&pins===0) type='gutter'; else if(before===10&&pins<=3) type='washout'; else if(before<10&&pins===before) type='spare'; else if(pins===0) type='miss'; const hookBase=(input?input.spin:0)/100; const natural=(lefty?-1:1)*(playerVisual(pl).twoHanded?1.2:.75); return {type,lefty,line:line||0,hook:natural+hookBase,impactSide:lefty?'left':'right'}; }
  function applyVisualLeave(gs,before,pins,meta){ const remain=Math.max(0,before-pins); if(before===10) gs.visualStanding=chooseFullRackLeave(remain,meta); else gs.visualStanding=reduceExistingLeave(gs.visualStanding||[],remain,meta); gs.lastVisual={remain,meta}; }

  function liveBowlingScore(gs){ if(!gs) return 0; const cs=cumulativeScores(gs); for(let i=9;i>=0;i--){if(cs[i]!==null&&cs[i]!==undefined)return cs[i];} return gs.frames.reduce((s,f)=>s+f.reduce((a,b)=>a+b,0),0); }
  function diffCell(label,val,type){return `<div class="champ-diff-cell ${type||''}"><span class="champ-diff-label">${label}</span><span class="champ-diff-val">${val}</span></div>`;}
  function differentialRow(pl,gameDiff,totalDiff){ const gameBehind=gameDiff<0?Math.abs(gameDiff):'—',totalBehind=totalDiff<0?Math.abs(totalDiff):'—',gameAhead=gameDiff>0?gameDiff:'—',totalAhead=totalDiff>0?totalDiff:'—'; return `<div class="champ-diff-row"><div class="champ-diff-name">${pl.emoji} ${pl.name}</div>${diffCell('Game Behind',gameBehind,gameDiff<0?'behind':'')}${diffCell('Total Behind',totalBehind,totalDiff<0?'behind':'')}${diffCell('Game Ahead',gameAhead,gameDiff>0?'ahead':'')}${diffCell('Total Ahead',totalAhead,totalDiff>0?'ahead':'')}</div>`; }
  function updateChampDifferentials(){ const el=document.getElementById('champDiffStrip'); if(!el||!arcade.gA||!arcade.gB)return; const aLive=liveBowlingScore(arcade.gA),bLive=liveBowlingScore(arcade.gB),aPrior=arcade.gamesA.reduce((x,y)=>x+y,0),bPrior=arcade.gamesB.reduce((x,y)=>x+y,0),gameDiff=aLive-bLive,totalDiff=(aPrior+aLive)-(bPrior+bLive); el.innerHTML=differentialRow(arcade.pA,gameDiff,totalDiff)+differentialRow(arcade.pB,-gameDiff,-totalDiff); }
  function lowerThirdMeta(pl){return `#${pl.seed||'—'} Seed · ${pl.championships||0} Career Ring${(pl.championships||0)===1?'':'s'} · ${tierJerseyText(pl)}`;}
  function toggleLowerThird(){ arcade.lowerThirdMinimized=!arcade.lowerThirdMinimized; const gs=arcade.gA&&arcade.gB?currentGameState():null; if(gs) updateLowerThird(gs.pl); updateChampDifferentials(); }
  function updateLowerThird(pl){ const el=document.getElementById('arcadeLowerThird'); if(!el||!pl)return; el.classList.toggle('minimized',!!arcade.lowerThirdMinimized); el.innerHTML=`<div class="lt-tag">BCM SN</div><div class="lt-main"><div class="lt-name">${pl.emoji} ${pl.name}</div><div class="lt-meta">${lowerThirdMeta(pl)}</div></div><button class="lt-toggle" id="btnLowerThirdToggle" type="button">${arcade.lowerThirdMinimized?'Expand':'Minimize'}</button>`; document.getElementById('btnLowerThirdToggle')?.addEventListener('click',toggleLowerThird); }
  function strikeStreakCount(gs){ const rolls=[]; gs.frames.forEach((f,idx)=>{if(!f.length)return;if(idx<9){if(f[0]===10)rolls.push(10);else rolls.push(-1);}else f.forEach(v=>rolls.push(v===10?10:-1));}); let count=0;for(let i=rolls.length-1;i>=0;i--){if(rolls[i]===10)count++;else break;}return count; }
  function showStreakBanner(label,sub){ const el=document.getElementById('streakBanner');if(!el)return;if(arcade.streakTimer)clearTimeout(arcade.streakTimer);el.innerHTML=`<div class="streak-kicker">Hot Streak</div><div class="streak-main">${label}</div><div class="streak-sub">${sub}</div>`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');arcade.streakTimer=setTimeout(()=>el.classList.remove('show'),arcadeMs(1325)); }
  function titleBeatDescriptor(gs){ const txt=computeNeedsText(gs),m=txt.match(/Needs (\d+)/);if(!m)return null;const pins=+m[1];if(!(arcade.gameIndex===2&&gs.frameIndex>=9&&pins>0&&pins<=gs.pinsStanding))return null;return {pins,text:txt,key:`${arcade.gameIndex}-${arcade.turn}-${gs.frameIndex}-${gs.frames[gs.frameIndex].length}-${pins}`}; }
  function showTitleBeat(desc,pl){const el=document.getElementById('titleBeatOverlay');if(!el||!desc||!pl)return;el.innerHTML=`<div class="title-beat-card"><div class="beat-kicker">Championship Point</div><div class="beat-main">${pl.name} Can Clinch</div><div class="beat-sub">${desc.text} on this shot</div></div>`;el.classList.add('show');}
  function hideTitleBeat(){const el=document.getElementById('titleBeatOverlay');if(el)el.classList.remove('show');}

  newBowlingGame = function(pl){return {pl,frames:Array.from({length:10},()=>[]),frameIndex:0,pinsStanding:10,complete:false,visualStanding:[0,1,2,3,4,5,6,7,8,9],lastVisual:null};};
  cloneBowlingGame = function(gs){return {pl:gs.pl,frames:gs.frames.map(f=>f.slice()),frameIndex:gs.frameIndex,pinsStanding:gs.pinsStanding,complete:gs.complete,visualStanding:(gs.visualStanding||[]).slice(),lastVisual:gs.lastVisual?{...gs.lastVisual}:null};};

  showBowlerSpeech = function(text,cls=''){ const el=document.getElementById('bowlerSpeech');if(!el||!text)return;if(arcade.speechTimer)clearTimeout(arcade.speechTimer);el.className='bowler-speech';if(cls)el.classList.add(cls);el.textContent=text;el.classList.add('show');arcade.speechTimer=setTimeout(()=>{const live=document.getElementById('bowlerSpeech');if(live)live.classList.remove('show');},arcadeMs(1450)); };
  showStrikeStinger = function(){const el=document.getElementById('strikeStinger');if(!el)return;if(arcade.stingerTimer)clearTimeout(arcade.stingerTimer);el.classList.remove('show');void el.offsetWidth;el.classList.add('show');arcade.stingerTimer=setTimeout(()=>el.classList.remove('show'),arcadeMs(900));};
  showCrowdPop = function(kind='pop'){const scene=document.querySelector('.lane-scene');if(!scene)return;setCrowdMood(kind==='explode'?'explode':kind==='strike'?'strike':kind==='spare'?'spare':'pop');scene.classList.remove('crowd-pop');void scene.offsetWidth;scene.classList.add('crowd-pop');setTimeout(()=>{scene.classList.remove('crowd-pop');if(document.querySelector('.lane-scene'))setCrowdMood('normal');},arcadeMs(930));};

  animateHumanThrow = function(rollMeta){
    const scene=document.querySelector('.lane-scene'),stage=document.getElementById('arcadeHumanStage'),root=document.querySelector('#arcadeHumanStage .bowler-avatar'),avatarBall=root&&root.querySelector('.avatar-ball'),laneBall=document.getElementById('arcadeBall'),pinDeck=document.getElementById('arcadePinDeck'),path=document.getElementById('releasePath');
    if(!scene||!stage||!root||!avatarBall||!laneBall||!pinDeck)return;
    const meta=(typeof rollMeta==='object'&&rollMeta)?rollMeta:{line:rollMeta||0,before:10,pins:0,pl:currentGameState().pl};
    const vis=meta.visual||makeVisualRollMeta(meta.pl||currentGameState().pl,meta.before||10,meta.pins||0,meta.input||null,meta.line||0);
    root.classList.remove('ready','celebrate','frustrated','spare-react');root.classList.add('throwing');
    root.animate([{bottom:'0px'},{bottom:'5px',offset:.22},{bottom:'13px',offset:.48},{bottom:'22px',offset:.72},{bottom:'18px'}],{duration:arcadeMs(950),easing:'cubic-bezier(.2,.72,.22,1)',fill:'forwards'});
    const sceneRect=scene.getBoundingClientRect(),pinRect=pinDeck.getBoundingClientRect();if(path){path.classList.add('active');setTimeout(()=>path.classList.remove('active'),arcadeMs(720));}
    setTimeout(()=>{if(!arcade.rolling)return;const handBall=document.querySelector('#arcadeHumanStage .avatar-ball');if(!handBall)return;const a=handBall.getBoundingClientRect(),startX=(a.left-sceneRect.left)+(a.width/2)-15,startY=(a.top-sceneRect.top)+(a.height/2)-15,lefty=!!vis.lefty;let targetX=(pinRect.left-sceneRect.left)+(pinRect.width/2)-6;if(vis.type==='strike')targetX+=lefty?-12:12;else if(vis.type==='brooklyn')targetX+=lefty?12:-12;else if(vis.type==='gutter')targetX=(lefty?sceneRect.width*.045:sceneRect.width*.955)-15;else if(vis.type==='washout')targetX+=vis.line>0?44:-44;else if(vis.type==='spare')targetX+=vis.line*.5;else targetX+=vis.line*.82;const targetY=(pinRect.top-sceneRect.top)+(pinRect.height*.54)-6;handBall.style.opacity='0';laneBall.classList.add('rolling');laneBall.classList.toggle('hit-gutter',vis.type==='gutter');laneBall.classList.toggle('hit-pocket',vis.type==='strike'||vis.type==='brooklyn');laneBall.style.opacity='1';laneBall.style.width='30px';laneBall.style.height='30px';laneBall.style.left=`${startX}px`;laneBall.style.top=`${startY}px`;laneBall.style.transform='none';const dx=targetX-startX,dy=targetY-startY,hook=(vis.type==='gutter'?0:(vis.hook||0)),curve=hook*32,mid1x=vis.type==='gutter'?dx*.28:dx*.22+curve*.25,mid2x=vis.type==='gutter'?dx*.62:dx*.62+curve*.95,mid3x=vis.type==='gutter'?dx*.86:dx*.86+curve*.35;laneBall.animate([{transform:'translate(0,0) scale(1) rotate(0deg)',opacity:1,offset:0},{transform:`translate(${mid1x}px,${dy*.12}px) scale(.95) rotate(110deg)`,opacity:1,offset:.22},{transform:`translate(${mid2x}px,${dy*.44}px) scale(.70) rotate(390deg)`,opacity:1,offset:.60},{transform:`translate(${mid3x}px,${dy*.80}px) scale(.48) rotate(720deg)`,opacity:1,offset:.86},{transform:`translate(${dx}px,${dy}px) scale(.36) rotate(980deg)`,opacity:1,offset:1}],{duration:arcadeMs(700),easing:vis.type==='gutter'?'cubic-bezier(.2,.55,.25,1)':'cubic-bezier(.15,.72,.22,1)',fill:'forwards'});},arcadeMs(430));
  };

  renderArcadePins = function(gs){ const deck=document.getElementById('arcadePinDeck');if(!deck||!gs)return;const pos=pinPositions();if(deck.querySelectorAll('.arcade-pin').length!==10){deck.innerHTML=pos.map((p,i)=>`<div class="arcade-pin standing" data-pin="${i}" style="left:${p[0]}%;top:${p[1]}%;--dx:0px;--dy:0px;--rot:0deg;"></div>`).join('');}const standingSet=new Set((gs.visualStanding||pinIndexPool()).slice());deck.querySelectorAll('.arcade-pin').forEach((el,i)=>{const down=!standingSet.has(i),dx=down?(((i%3)-1)*9+(i>5?5:-2)):0,dy=down?(6+(i%4)*2):0,rot=down?(-82+((i*29)%154)):0,hit=gs.lastVisual&&gs.lastVisual.meta&&['washout','miss','gutter'].includes(gs.lastVisual.meta.type)?'light-hit':'';el.style.setProperty('--dx',`${dx}px`);el.style.setProperty('--dy',`${dy}px`);el.style.setProperty('--rot',`${rot}deg`);el.className=`arcade-pin ${down?'down '+hit:'standing'}`;}); };

  chooseRollPins = function(pl,standing,input){ const avg=calcBlendedAvg(pl)+(pl.formModifier||0),skill=Math.max(0,Math.min(1,(avg-70)/170)),q=inputQuality(input);if(standing===10){const gutterP=Math.max(.012,Math.min(.08,.018+(1-skill)*.03+Math.max(0,.58-q)*.09));if(Math.random()<gutterP)return 0;const strikeP=Math.max(.035,Math.min(.62,.045+skill*.47+(q-.5)*.18));if(Math.random()<strikeP)return 10;const mu=5.1+skill*3.15+(q-.5)*1.4;return Math.max(1,Math.min(9,Math.round(mu+gaussian()*1.45)));}const spareP=Math.max(.07,Math.min(.9,.2+skill*.53+(q-.5)*.24-standing*.012));if(Math.random()<spareP)return standing;const mu=standing*(.38+skill*.38+q*.13);return Math.max(0,Math.min(standing-1,Math.round(mu+gaussian()*Math.max(.7,standing*.14)))); };

  arcadeComment = function(pl,pins,before,frame,q){const v=playerVisual(pl);let text;if(before===10&&pins===10){text=`💥 STRIKE! ${pl.emoji} ${pl.name} flushes the pocket in frame ${frame+1}.`;if(v.quoteStrike)text+=` ${v.quoteStrike}`;}else if(pins===before){text=`✅ ${pl.name} cleans up the spare in frame ${frame+1}.`;if(v.quoteSpare)text+=` ${v.quoteSpare}`;else if(v.personality==='Businesslike')text+=` Clean, simple, and professional from ${pl.name}.`;}else if(pins===0&&before===10){text=`😬 Gutter ball for ${pl.name}. Nothing down.`;if(v.quoteBad)text+=` ${v.quoteBad}`;}else if(pins===0){text=`😬 ${pl.name} misses the spare attempt. Nothing down.`;if(v.quoteBad)text+=` ${v.quoteBad}`;}else if(before===10&&pins===9)text=`🎯 ${pl.name} leaves a lonely pin after a nine-count.`;else if(before===10&&pins<=5)text=`⚠️ Trouble for ${pl.name}: only ${pins} on the first ball. ${v.quoteBad||''}`.trim();else{text=`${pl.emoji} ${pl.name} knocks down ${pins}${before<10?` of the ${before} remaining`:''}.`;if(pl.id==='woo')text+=` ${v.quoteBad}`;else if(pl.id==='gavin'&&pins>=7)text+=` That trademark spin did some work.`;else if(pl.id==='carter'&&pins>=8)text+=` Carter stayed way left and loved the result.`;}if(q>.9&&pins<before)text+=` The release was nearly perfect, but the pins didn't cooperate.`;arcade.commentary.push(text);};

  renderArcadeLive = function(){ if(!arcade.gA||!arcade.gB)return;const gs=currentGameState(),v=playerVisual(gs.pl);document.getElementById('arcadeScoreboard').innerHTML=scoreRowHtml(arcade.gA)+scoreRowHtml(arcade.gB);updateLowerThird(gs.pl);updateChampDifferentials();setArcadeSpeed(arcade.speed||1);const bow=document.getElementById('arcadeBowler');if(bow)bow.innerHTML=`<div class="lane-bowler-copy"><div class="lane-bowler-name">${gs.pl.emoji} ${gs.pl.name}</div><div class="lane-bowler-meta">${v.style} · ${v.shirtLabel}${v.personality?' · '+v.personality:''}</div></div>`;const human=document.getElementById('arcadeHumanStage');if(human)human.innerHTML=bowlerPreviewHtml(gs.pl,'lane',arcade.rolling?'throwing':'ready');const laneBall=document.getElementById('arcadeBall');if(laneBall){laneBall.style.background=`radial-gradient(circle at 30% 28%, rgba(255,255,255,.95), color-mix(in srgb, ${v.ball} 82%, #fff 18%) 20%, ${v.ball} 55%, #000 135%)`;if(!arcade.rolling)laneBall.style.opacity='0';}const meta=document.getElementById('arcadeTurnMeta');if(meta)meta.textContent=`Frame ${Math.min(10,gs.frameIndex+1)} · ${gs.pinsStanding} pins standing`;const marker=document.getElementById('pocketMarker');if(marker)marker.style.left=`calc(50% + ${arcade.targetAim*.55}px)`;renderArcadePins(gs);const comm=document.getElementById('arcadeCommentary');if(comm)comm.innerHTML=arcade.commentary.slice(-4).map((x,i,a)=>`<div class="commentary-line ${i===a.length-1?'latest':''}">${x}</div>`).join('');const scene=document.querySelector('.lane-scene');if(scene){scene.classList.toggle('frame-ten',gs.frameIndex>=9||otherGameState().frameIndex>=9);if(gs.frameIndex>=9||otherGameState().frameIndex>=9)setCrowdMood('tense');else if(!arcade.rolling)setCrowdMood('normal');}updateNeedsOverlay();renderArcadeControls(); };

  advanceArcadeTurn = function(){if(!arcade.active||arcade.rolling)return;if(arcade.gA.complete&&arcade.gB.complete){finishArcadeGame();return;}const gs=currentGameState();if(gs.complete){if(arcade.turn==='A')arcade.turn='B';else{arcade.turn='A';arcade.frameRound++;}arcade.targetAim=Math.round((Math.random()-.5)*34);arcade.titleBeatKey=null;renderArcadeLive();return advanceArcadeTurn();}renderArcadeLive();const beat=titleBeatDescriptor(gs);if(beat&&arcade.titleBeatKey!==beat.key){arcade.titleBeatKey=beat.key;showTitleBeat(beat,gs.pl);setCrowdMood('tense');arcade.timers.push(setTimeout(()=>{hideTitleBeat();advanceArcadeTurn();},arcadeMs(1100)));return;}hideTitleBeat();if(!arcade.controlId||gs.pl.id!==arcade.controlId)arcade.timers.push(setTimeout(()=>performArcadeRoll(null),arcadeMs(820)));};

  performArcadeRoll = function(input){if(arcade.rolling)return;arcade.rolling=true;if(arcade.powerRaf)cancelAnimationFrame(arcade.powerRaf);arcade.powerRaf=null;const gs=currentGameState(),before=gs.pinsStanding,frame=gs.frameIndex,pins=chooseRollPins(gs.pl,before,input),q=inputQuality(input);let frameDone=false;const line=input?(input.aim+input.spin*.34):arcade.targetAim+(Math.random()-.5)*22,visualMeta=makeVisualRollMeta(gs.pl,before,pins,input,line);playArcadeSound('roll');renderArcadeLive();requestAnimationFrame(()=>animateHumanThrow({line,before,pins,input,pl:gs.pl,visual:visualMeta}));arcade.timers.push(setTimeout(()=>{const beforeFrame=gs.frameIndex;applyBowlingRoll(gs,pins);applyVisualLeave(gs,before,pins,visualMeta);frameDone=gs.complete||gs.frameIndex!==beforeFrame;playArcadeSound(pins===before?'strike':'pins');arcadeComment(gs.pl,pins,before,frame,q);renderArcadePins(gs);showBowlingReaction(pins,before);if(before===10&&pins===10){showStrikeStinger();const streak=strikeStreakCount(gs);if(streak===3)showStreakBanner('Turkey!','Three straight strikes on the title pair');else if(streak===5)showStreakBanner('5-BAGGER!','The crowd is losing it right now');}if(before===10&&pins===10)showCrowdPop('strike');else if(before<10&&pins===before)showCrowdPop('spare');else if(frame>=9)showCrowdPop('pop');maybeSignatureSpeech(gs.pl,pins,before);const board=document.getElementById('arcadeScoreboard');if(board)board.innerHTML=scoreRowHtml(arcade.gA)+scoreRowHtml(arcade.gB);const comm=document.getElementById('arcadeCommentary');if(comm)comm.innerHTML=arcade.commentary.slice(-4).map((x,i,a)=>`<div class="commentary-line ${i===a.length-1?'latest':''}">${x}</div>`).join('');updateNeedsOverlay();updateChampDifferentials();arcade.titleBeatKey=null;},arcadeMs(1160)));arcade.timers.push(setTimeout(()=>{const b=document.getElementById('arcadeBall');if(b){b.getAnimations().forEach(a=>a.cancel());b.classList.remove('rolling','hit-pocket','hit-gutter');b.style.opacity='0';}if(gs.pinsStanding===10&&!gs.complete)gs.visualStanding=[0,1,2,3,4,5,6,7,8,9];if(frameDone){if(arcade.turn==='A')arcade.turn='B';else{arcade.turn='A';arcade.frameRound++;}arcade.targetAim=Math.round((Math.random()-.5)*34);}arcade.rolling=false;advanceArcadeTurn();},arcadeMs(1780)));};

  startArcadeGame = function(){arcade.gA=newBowlingGame(arcade.pA);arcade.gB=newBowlingGame(arcade.pB);arcade.turn='A';arcade.frameRound=0;arcade.targetAim=Math.round((Math.random()-.5)*34);arcade.rolling=false;if(!arcade.crowdSeed)arcade.crowdSeed=Math.floor(Math.random()*999999);const stage=document.getElementById('arcadeStage');stage.innerHTML=`<div class="walkout"><div class="series-score">${playoffs.M[arcade.key].roundLabel} · Game ${arcade.gameIndex+1} of 3 · ${arcadeSeriesLabel()}</div><div class="walkout-main">Championship Pair</div></div><div class="tv-scoreboard" id="arcadeScoreboard"></div><div class="champ-diff-strip" id="champDiffStrip"></div><div class="arcade-arena"><div class="lane-scene" data-crowd="normal"><div class="crowd"><div class="crowd-inner" id="arcadeCrowd"></div></div><div class="lane-light"></div><div class="gutter left"></div><div class="gutter right"></div><div class="arcade-lane"></div><div class="foul-line"></div><div class="pocket-marker" id="pocketMarker"></div><div class="pin-deck" id="arcadePinDeck"></div><div class="arcade-ball" id="arcadeBall"></div><div class="release-path" id="releasePath"></div><div class="human-stage" id="arcadeHumanStage"></div><div class="strike-stinger" id="strikeStinger"><div class="wallaby">🦘</div><div class="stinger-copy"><span class="stinger-bcm">BCM Bowling</span><span class="stinger-strike">STRIKE!</span></div></div><div class="streak-banner" id="streakBanner"></div><div class="title-beat-overlay" id="titleBeatOverlay"></div><div class="needs-overlay" id="needsOverlay"></div><div class="arcade-lowerthird" id="arcadeLowerThird"></div><div class="lane-hud"><div class="bowler" id="arcadeBowler"></div><div class="turnmeta" id="arcadeTurnMeta"></div></div></div><div class="arcade-sidepanel"><div class="commentary-box"><div class="commentary-title">Live Commentary</div><div id="arcadeCommentary"></div></div><div><div class="control-title">Bowling Controls</div><div id="arcadeControls"></div><div class="arcade-speed"><span class="speed-label">Watch Speed</span><button class="ghost" type="button" id="btnSpeed1">1x</button><button class="ghost" type="button" id="btnSpeed2">2x</button></div></div><div class="controls"><button class="ghost" id="btnArcadeAutoRest">Auto Bowl Rest</button><button class="ghost" id="btnArcadeSimGame">Sim Rest of Game</button></div></div></div>`;arcade.titleBeatKey=null;document.getElementById('btnArcadeAutoRest').addEventListener('click',()=>{arcade.controlId=null;advanceArcadeTurn();});document.getElementById('btnArcadeSimGame').addEventListener('click',simRestOfArcadeGame);document.getElementById('btnSpeed1').addEventListener('click',()=>setArcadeSpeed(1));document.getElementById('btnSpeed2').addEventListener('click',()=>setArcadeSpeed(2));renderChampionshipCrowd();renderArcadeLive();advanceArcadeTurn();};
})();